#!/usr/bin/env node
/**
 * Regenerates supabase/seed.sql from the hosted project's public content.
 *
 *   node scripts/build-seed.mjs
 *
 * Reads through PostgREST with the **anon** key from .env, which is the useful
 * part: the anon role sees exactly what a visitor sees. Draft posts, the
 * contact inbox and the admin user table are invisible to it and therefore
 * cannot end up in a committed file by accident. The boundary is enforced by
 * the database rather than by a list of tables to avoid.
 *
 * The result is a local database that reproduces the real site, so `db reset`
 * gives you something worth looking at and the migrations job in CI proves the
 * schema can carry the actual data rather than a toy fixture.
 *
 * Columns that only exist after 20260910000001_project_showcase.sql are skipped
 * when the hosted project has not had that migration applied yet, so this keeps
 * working either side of it.
 */

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const ROOT = path.join(import.meta.dirname, "..");
const OUT = path.join(ROOT, "supabase", "seed.sql");

/** Tables to mirror, in insert order. Anything not readable by anon is absent. */
const TABLES = [
  "personal_info",
  "projects",
  "experience",
  "education",
  "skills",
  "courses",
  "achievements",
  "languages",
  "blog_posts",
];

/**
 * Never copied into the seed.
 *
 * `id` and the timestamps are regenerated by the column defaults: carrying them
 * over would pin every row to a UUID and a creation date from another database,
 * and `updated_at` in particular would make a fresh seed look stale.
 */
const SKIP_COLUMNS = new Set(["id", "created_at", "updated_at"]);

function env() {
  const text = fs.readFileSync(path.join(ROOT, ".env"), "utf8");
  const read = (key) =>
    text.match(new RegExp(`^${key}\\s*=\\s*"?([^"\\n]+)"?`, "m"))?.[1]?.trim();
  const url = read("VITE_SUPABASE_URL");
  const key = read("VITE_SUPABASE_PUBLISHABLE_KEY") ?? read("VITE_SUPABASE_ANON_KEY");
  if (!url || !key) {
    throw new Error("VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY must be in .env");
  }
  return { url, key };
}

function fetchTable({ url, key }, table) {
  const body = execFileSync(
    "curl",
    ["-sS", `${url}/rest/v1/${table}?select=*`, "-H", `apikey: ${key}`],
    { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 }
  );
  const parsed = JSON.parse(body);
  if (!Array.isArray(parsed)) {
    throw new Error(`${table}: ${parsed.message ?? body.slice(0, 200)}`);
  }
  return parsed;
}

/** One SQL literal. Arrays and JSON have to be told apart before quoting. */
function literal(value) {
  if (value === null || value === undefined) return "null";
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") return String(value);
  if (Array.isArray(value)) {
    // A Postgres text[]. An empty one is not null: the difference is visible in
    // the UI, where null means "not set" and {} means "set to nothing".
    if (value.length === 0) return "'{}'";
    // An array of objects is jsonb, not text[].
    if (value.some((v) => v !== null && typeof v === "object")) {
      return `${quote(JSON.stringify(value))}::jsonb`;
    }
    return `array[${value.map((v) => quote(String(v))).join(", ")}]`;
  }
  if (typeof value === "object") return `${quote(JSON.stringify(value))}::jsonb`;
  return quote(String(value));
}

const quote = (s) => `'${s.replace(/'/g, "''")}'`;

const { url, key } = env();
const sections = [];
let total = 0;

for (const table of TABLES) {
  const rows = fetchTable({ url, key }, table);
  if (rows.length === 0) {
    sections.push(`-- ${table}: no rows visible to the anon role.\n`);
    continue;
  }
  const columns = Object.keys(rows[0]).filter((c) => !SKIP_COLUMNS.has(c));
  const values = rows.map(
    (row) => `  (${columns.map((c) => literal(row[c])).join(", ")})`
  );
  sections.push(
    `insert into public.${table} (${columns.join(", ")}) values\n` +
      `${values.join(",\n")}\non conflict do nothing;\n`
  );
  total += rows.length;
}

const header = `-- Local development seed. GENERATED - do not edit by hand.
--
--   node scripts/build-seed.mjs
--
-- A mirror of the hosted project's **public** content, read with the anon key,
-- so a local \`supabase db reset\` reproduces the real site rather than a toy
-- fixture. ${total} rows across ${TABLES.length} tables.
--
-- Because it is read as anon, it contains exactly what any visitor to the live
-- site can already see. Draft posts, the contact inbox and the admin user table
-- are invisible to that role and cannot appear here.
--
-- Applied by \`supabase db reset\`. Never applied to the hosted project.

`;

fs.writeFileSync(OUT, header + sections.join("\n"));
console.log(`Wrote ${path.relative(ROOT, OUT)}: ${total} rows`);
