// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqmsihngmlnbophikpqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxbXNpaG5nbWxuYm9waGlrcHFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMTE1NTcsImV4cCI6MjA3Mzg4NzU1N30.rnuDaplenrvWEe_ivRtP3hOhOvUetyCD6Re9VjSpvTM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});